name: angular_document_management
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Matias Sala <email@example.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0
  angular_bloc: ^0.7.0
  common_sales_management:
    path: ../common_sales_management
  pwa: ^0.1.12

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.2.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.5.1
  sass_builder: ^2.1.2